version: '3.8'

services:
  # --- BANCO DE DADOS (PostgreSQL) ---
  postgres:
    image: postgres:15
    container_name: finops_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: financas_pessoais
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finops_net

  # --- INTERFACE VISUAL (pgAdmin) ---
  # Acesse em: http://localhost:5050
  pgadmin:
    image: dpage/pgadmin4
    container_name: finops_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - finops_net

volumes:
  postgres_data:

networks:
  finops_net: